version: "3.9"
services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: ["zap.sh","-daemon","-port","8090","-host","0.0.0.0"]
    ports: ["8090:8090"]
    user: zap
    restart: unless-stopped
volumes:
  ollama:
